import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Hero-section/Header";
import Footer from "./components/Hero-section/Footer";

const poppinsBlack = Poppins({
  weight: ["900"],
  variable: "--font-poppins-black",
  subsets: ["latin"],
});

const poppinsMedium = Poppins({
  weight: ["500"],
  variable: "--font-poppins-medium",
  subsets: ["latin"],
});

const poppinsRegular = Poppins({
  weight: ["400"],
  variable: "--font-poppins-regular",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppinsBlack.variable} ${poppinsMedium.variable} ${poppinsRegular.variable}`}>
      <body>



      <Header/>
        {children}

        <Footer/>



      </body>
    </html>
  );
}
